/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FormatAssistantPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/api-profiles.ts
var MAX_API_PROFILES = 8;
function createApiProfileFromSettings(settings, name) {
  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    name: toProfileName(name, settings),
    baseUrl: settings.baseUrl,
    apiKey: settings.apiKey,
    model: settings.model,
    maxTokens: settings.maxTokens,
    temperature: settings.temperature,
    providerType: settings.providerType,
    timeoutSeconds: settings.timeoutSeconds
  };
}
function normalizeApiProfiles(value) {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item) => {
    return Boolean(
      item && typeof item.id === "string" && typeof item.name === "string" && typeof item.baseUrl === "string" && typeof item.apiKey === "string" && typeof item.model === "string" && typeof item.maxTokens === "number" && typeof item.temperature === "number" && item.providerType === "openai-compatible" && typeof item.timeoutSeconds === "number"
    );
  }).slice(0, MAX_API_PROFILES);
}
function applyApiProfile(settings, profile) {
  settings.baseUrl = profile.baseUrl;
  settings.apiKey = profile.apiKey;
  settings.model = profile.model;
  settings.maxTokens = profile.maxTokens;
  settings.temperature = profile.temperature;
  settings.providerType = profile.providerType;
  settings.timeoutSeconds = profile.timeoutSeconds;
  settings.activeApiProfileId = profile.id;
}
function toProfileName(name, settings) {
  const normalized = name.trim();
  if (normalized) {
    return normalized.length > 32 ? `${normalized.slice(0, 32)}...` : normalized;
  }
  return settings.model.trim() || "API Profile";
}

// src/prompts.ts
var BASE_SYSTEM_PROMPT = `\u4F60\u662F Obsidian Markdown \u7B14\u8BB0\u6574\u7406\u52A9\u624B\u3002

\u901A\u7528\u89C4\u5219\uFF1A
1. \u53EA\u5904\u7406\u7528\u6237\u63D0\u4F9B\u7684\u8F93\u5165\u6587\u672C\u672C\u8EAB\u3002
2. \u4E0D\u8981\u6DFB\u52A0\u8F93\u5165\u6587\u672C\u4E2D\u4E0D\u5B58\u5728\u7684\u4E8B\u5B9E\u3002
3. \u4E0D\u8981\u7F16\u9020\u65E5\u671F\u3001\u4EBA\u7269\u3001\u5730\u70B9\u3001\u6807\u9898\u3001\u6807\u7B7E\u3001\u7ED3\u8BBA\u3002
4. \u4E0D\u8981\u6DFB\u52A0 frontmatter\u3002
5. \u4E0D\u8981\u6DFB\u52A0 date\u3001tags\u3001title \u7B49\u5143\u6570\u636E\u3002
6. \u4E0D\u8981\u6839\u636E\u6587\u4EF6\u540D\u63A8\u65AD\u65E5\u671F\u6216\u6807\u9898\u3002
7. \u4E0D\u8981\u8865\u5168\u6A21\u677F\u3002
8. \u4E0D\u8981\u8F93\u51FA bash\u3001shell\u3001\u7EC8\u7AEF\u547D\u4EE4\u3002
9. \u4E0D\u8981\u89E3\u91CA\u4F60\u7684\u5904\u7406\u8FC7\u7A0B\u3002
10. \u4E0D\u8981\u8F93\u51FA\u201C\u4E0B\u9762\u662F\u6574\u7406\u7ED3\u679C\u201D\u7B49\u989D\u5916\u5F00\u5934\u3002
11. \u53EA\u8F93\u51FA\u6700\u7EC8 Markdown\u3002
12. \u4FDD\u7559\u539F\u610F\u3002
13. \u53EF\u4EE5\u505A\u9002\u5EA6\u5206\u6BB5\u3001\u5217\u8868\u5316\u3001\u6807\u9898\u5C42\u7EA7\u8C03\u6574\u548C\u8F7B\u5FAE\u63AA\u8F9E\u6E05\u7406\u3002
14. \u4FDD\u6301 Obsidian \u517C\u5BB9\uFF1A
    - wikilink \u4FDD\u6301\u4E3A [[...]]
    - task \u4FDD\u6301\u4E3A - [ ] / - [x]
    - callout \u4FDD\u6301\u4E3A > [!type]
    - Markdown \u6807\u9898\u4F7F\u7528 # \u5C42\u7EA7
15. \u5982\u679C\u8F93\u5165\u6587\u672C\u5F88\u77ED\uFF0C\u4E0D\u8981\u5F3A\u884C\u6269\u5C55\u6210\u590D\u6742\u7ED3\u6784\u3002`;
var OBSIDIAN_MARKDOWN_PROMPT = `\u4F60\u6B63\u5728\u6267\u884C\u201CObsidian Markdown \u8F7B\u91CF\u6574\u7406\u6A21\u5F0F\u201D\u3002

\u6574\u7406\u76EE\u6807\uFF1A
1. \u53EA\u505A\u57FA\u7840 Markdown \u683C\u5F0F\u6574\u7406\u3002
2. \u4F18\u5148\u6539\u5584\u65AD\u53E5\u3001\u5206\u6BB5\u3001\u5217\u8868\u548C\u6807\u9898\u5C42\u7EA7\u3002
3. \u4E0D\u8981\u751F\u6210\u590D\u6742\u7ED3\u6784\u3002
4. \u4E0D\u8981\u6DFB\u52A0\u8F93\u5165\u4E2D\u4E0D\u5B58\u5728\u7684 frontmatter\u3001\u6807\u9898\u3001\u6A21\u677F\u5C0F\u8282\u6216\u5143\u6570\u636E\u3002
5. \u5982\u679C\u8F93\u5165\u5F88\u77ED\uFF0C\u53EA\u8F93\u51FA\u66F4\u6E05\u695A\u7684\u539F\u6587\u6574\u7406\u7248\u3002`;
var NOTE_ORGANIZE_PROMPT = `\u4F60\u6B63\u5728\u6267\u884C\u201C\u7B14\u8BB0\u6574\u7406\u6A21\u5F0F\u201D\u3002

\u6574\u7406\u76EE\u6807\uFF1A
1. \u5C06\u8F93\u5165\u5185\u5BB9\u6574\u7406\u6210\u6E05\u6670\u7684 Obsidian Markdown \u7B14\u8BB0\u3002
2. \u4F18\u5148\u63D0\u70BC\u6982\u5FF5\u3001\u516C\u5F0F\u3001\u7ED3\u8BBA\u3001\u6761\u4EF6\u3001\u6613\u9519\u70B9\u548C\u5F85\u8FFD\u95EE\u95EE\u9898\u3002
3. \u5982\u679C\u8F93\u5165\u4E2D\u5305\u542B\u516C\u5F0F\uFF0C\u8BF7\u4FDD\u7559\u516C\u5F0F\uFF0C\u5E76\u8865\u5145\u9002\u7528\u6761\u4EF6\u3002
4. \u5982\u679C\u8F93\u5165\u4E2D\u5305\u542B\u63A8\u5BFC\uFF0C\u8BF7\u4FDD\u7559\u5173\u952E\u6B65\u9AA4\uFF0C\u4E0D\u8981\u8DF3\u5F97\u592A\u5927\u3002
5. \u5982\u679C\u8F93\u5165\u4E2D\u5305\u542B\u591A\u4E2A\u6982\u5FF5\uFF0C\u8BF7\u7528\u5C0F\u6807\u9898\u5206\u5C42\u3002
6. \u5982\u679C\u8F93\u5165\u5185\u5BB9\u8F83\u77ED\uFF0C\u53EA\u505A\u8F7B\u91CF\u6574\u7406\uFF0C\u4E0D\u8981\u5F3A\u884C\u751F\u6210\u5B8C\u6574\u7AE0\u8282\u3002
7. \u4E0D\u8981\u6DFB\u52A0\u8F93\u5165\u4E2D\u4E0D\u5B58\u5728\u7684\u77E5\u8BC6\u70B9\u3002
8. \u4E0D\u8981\u8865\u5145\u672A\u7ECF\u8F93\u5165\u652F\u6301\u7684\u80CC\u666F\u4ECB\u7ECD\u3002

\u63A8\u8350\u8F93\u51FA\u7ED3\u6784\uFF1A
\u5982\u679C\u8F93\u5165\u5185\u5BB9\u8F83\u5B8C\u6574\uFF0C\u53EF\u4F7F\u7528\uFF1A

## \u6838\u5FC3\u5185\u5BB9

## \u5173\u952E\u516C\u5F0F\u4E0E\u6761\u4EF6

## \u6613\u9519\u70B9

## \u5F85\u8FFD\u95EE\u95EE\u9898

\u4F46\u5982\u679C\u8F93\u5165\u5F88\u77ED\uFF0C\u53EF\u4EE5\u53EA\u4F7F\u7528\u5217\u8868\uFF0C\u4E0D\u8981\u5F3A\u884C\u751F\u6210\u6240\u6709\u6807\u9898\u3002`;
var DIARY_ORGANIZE_PROMPT = `\u4F60\u6B63\u5728\u6267\u884C\u201C\u65E5\u8BB0\u6574\u7406\u6A21\u5F0F\u201D\u3002

\u6574\u7406\u76EE\u6807\uFF1A
1. \u4FDD\u7559\u7528\u6237\u539F\u59CB\u8BED\u6C14\u548C\u771F\u5B9E\u611F\uFF0C\u4E0D\u8981\u6539\u5F97\u592A\u6B63\u5F0F\uFF0C\u4E0D\u8981\u6DFB\u52A0\u60C5\u7EEA\u5224\u65AD\u6216\u5FC3\u7406\u5206\u6790\uFF0C\u4E0D\u8981\u6269\u5199\u6210\u9E21\u6C64\u6216\u603B\u7ED3\u3002
2. \u4E0D\u8981\u6DFB\u52A0 frontmatter\u3001\u65E5\u671F\u6807\u9898\uFF0C\u6216\u8F93\u5165\u4E2D\u4E0D\u5B58\u5728\u7684\u5185\u5BB9\u3002

\u7ED3\u6784\u5904\u7406\uFF1A
3. \u5982\u679C\u539F\u6587\u5E26\u6709\u65F6\u95F4\u7EBF\u7D22\uFF08\u65E9 / \u4E0A\u5348 / \u4E0B\u5348 / \u665A / \u5177\u4F53\u65F6\u95F4\uFF09\uFF0C\u8BF7\u4FDD\u7559\u8FD9\u4E2A\u65F6\u95F4\u987A\u5E8F\u4F5C\u4E3A\u4E3B\u7ED3\u6784\uFF0C\u4E0D\u8981\u6253\u6563\u91CD\u6392\u3002
4. \u9ED8\u8BA4\u53EA\u505A\u8F7B\u91CF\u6574\u7406\uFF1A\u5206\u884C\u3001\u628A\u540C\u4E00\u65F6\u6BB5\u7684\u4E8B\u9879\u7406\u987A\u3002\u8F93\u5165\u5F88\u77ED\u65F6\u4E0D\u8981\u6DFB\u52A0 ## \u5C0F\u6807\u9898\u3002

\u4EFB\u52A1\u5224\u5B9A\uFF08\u5173\u952E\uFF09\uFF1A
5. \u5148\u5224\u65AD\u6BCF\u6761\u5C5E\u4E8E\u201C\u4EFB\u52A1\u201D\u8FD8\u662F\u201C\u751F\u6D3B\u8BB0\u5F55\u201D\uFF1A
   - \u4EFB\u52A1\uFF1A\u53EF\u6267\u884C\u7684\u5B66\u4E60 / \u5DE5\u4F5C\u4E8B\u9879\uFF0C\u4F8B\u5982\u505A\u4F5C\u4E1A\u3001\u590D\u4E60\u3001\u5199\u62A5\u544A\u3001\u505A\u9879\u76EE\u3001\u63A8\u8FDB\u67D0\u4EF6\u4E8B\u3002
   - \u751F\u6D3B\u8BB0\u5F55\uFF1A\u8D77\u5E8A\u3001\u5403\u996D\u3001\u62FF\u5FEB\u9012\u3001\u8EAB\u4F53\u72B6\u6001\u3001\u5FC3\u60C5\u7B49\u3002
6. \u6240\u6709\u201C\u4EFB\u52A1\u201D\u4E00\u5F8B\u6807\u6210\u672A\u5B8C\u6210\u5F85\u529E - [ ]\uFF0C\u7531\u7528\u6237\u4E4B\u540E\u81EA\u5DF1\u52FE\u9009\u3002\u5373\u4F7F\u539F\u6587\u5199\u4E86\u201C\u505A\u5B8C / \u5B8C\u6210\u201D\uFF0C\u4E5F\u7528 - [ ]\uFF0C\u7EDD\u4E0D\u8981\u81EA\u52A8\u6807\u6210 - [x]\u3002
7. \u4FDD\u7559\u7528\u6237\u539F\u6709\u6279\u6CE8\uFF08\u5982\u201C\u5B9E\u9645\uFF1A\u6CA1\u505A\u201D\uFF09\uFF0C\u4E0D\u8981\u66FF\u6362\u6210\u6A21\u677F\u8BCD\u3002
8. \u5BF9\u201C\u751F\u6D3B\u8BB0\u5F55\u201D\u4FDD\u6301\u666E\u901A bullet\uFF0C\u4E0D\u8981\u8F6C\u6210 checkbox\u3002
9. \u53EA\u6574\u7406\u539F\u6587\u5DF2\u6709\u7684\u4E8B\u9879\uFF0C\u4E0D\u8981\u51ED\u7A7A\u7F16\u9020\u4EFB\u52A1\u3002

\u793A\u4F8B\uFF1A
\u8F93\u5165\uFF1A
\u4E0A\u5348\uFF1A\u539F\u5B50\u505A\u5B8C\uFF0C\u590D\u4E60\u7B2C\u4E09\u7AE0\uFF08\u5B9E\u9645\uFF1A\u6CA1\u505A\uFF09
\u4E0B\u5348\uFF1A\u5199\u5927\u7269\u62A5\u544A
\u8F93\u51FA\uFF1A
- \u4E0A\u5348\uFF1A
  - [ ] \u539F\u5B50\u505A\u5B8C
  - [ ] \u590D\u4E60\u7B2C\u4E09\u7AE0\uFF08\u5B9E\u9645\uFF1A\u6CA1\u505A\uFF09
- \u4E0B\u5348\uFF1A
  - [ ] \u5199\u5927\u7269\u62A5\u544A`;
var REVIEW_CARD_PROMPT = "\u538B\u7F29\u4E3A\u590D\u4E60\u5361\u7247\uFF1A\n\u5C06\u5185\u5BB9\u538B\u7F29\u6210\u9AD8\u5BC6\u5EA6\u590D\u4E60\u7248\u3002\u4F18\u5148\u4FDD\u7559\u7ED3\u8BBA\u3001\u516C\u5F0F\u3001\u6761\u4EF6\u3001\u5173\u952E\u8BCD\u3001\u6613\u9519\u70B9\u548C\u6700\u77ED\u5FC5\u8981\u89E3\u91CA\u3002\u5C3D\u91CF\u77ED\u3001\u51C6\u3001\u53EF\u626B\u8BFB\uFF0C\u4F46\u4E0D\u8981\u9057\u6F0F\u539F\u6587\u5173\u952E\u903B\u8F91\uFF0C\u4E0D\u8981\u7F16\u9020\u5185\u5BB9\u3002";
var WIKI_CANDIDATES_PROMPT = "\u63D0\u53D6 Wiki \u5019\u9009\u6761\u76EE\uFF1A\n\u4ECE\u5185\u5BB9\u4E2D\u63D0\u53D6\u9002\u5408\u5355\u72EC\u6C89\u6DC0\u4E3A Wiki \u7684\u6982\u5FF5\u3001\u516C\u5F0F\u3001\u65B9\u6CD5\u3001\u5B9A\u7406\u3001\u6A21\u578B\u6216\u5B9E\u9A8C\u672F\u8BED\u3002\u8F93\u51FA\u65F6\u6309\u6761\u76EE\u5217\u51FA\uFF0C\u6BCF\u4E2A\u6761\u76EE\u53EA\u4FDD\u7559\u6700\u5C0F\u5FC5\u8981\u5B9A\u4E49\u3001\u7528\u9014\u6216\u533A\u5206\u70B9\u3002\u4E0D\u8981\u81EA\u52A8\u521B\u5EFA\u94FE\u63A5\uFF0C\u4E0D\u8981\u6269\u5199\u6210\u5B8C\u6574\u6587\u7AE0\u3002";
var CONCISE_PROMPT = "\u8BF7\u5C06\u8F93\u5165\u6587\u672C\u7CBE\u7B80\u4E3A\u66F4\u77ED\u3001\u66F4\u6E05\u695A\u7684 Markdown\uFF0C\u4E0D\u4E22\u5931\u6838\u5FC3\u516C\u5F0F\u3001\u9002\u7528\u6761\u4EF6\u3001\u5B9A\u4E49\u3001\u9650\u5236\u548C\u5173\u952E\u7ED3\u8BBA\u3002";
var MODE_RUNTIME = {
  // note/course produce longer structured output -> larger budget, longer wait.
  "note-organize": { maxTokens: 2e3, timeoutSeconds: 60 },
  "course-note": { maxTokens: 2e3, timeoutSeconds: 60 },
  // diary output is usually shorter and faster.
  "diary-organize": { maxTokens: 900, timeoutSeconds: 30 }
};
function resolveModeRuntime(mode, settings) {
  var _a, _b, _c;
  const override = (_a = MODE_RUNTIME[mode]) != null ? _a : {};
  return {
    maxTokens: (_b = override.maxTokens) != null ? _b : settings.maxTokens,
    timeoutSeconds: (_c = override.timeoutSeconds) != null ? _c : settings.timeoutSeconds
  };
}
var FORMAT_MODE_LABELS = {
  "obsidian-markdown": "Obsidian Markdown",
  "note-organize": "Note Organize",
  "diary-organize": "Diary Organize",
  "course-note": "Course Note",
  "review-card": "Review Card",
  "wiki-candidates": "Wiki Candidates",
  concise: "Concise",
  custom: "Custom Instruction"
};
var FORMAT_TASKS = [
  {
    id: "format-selection-as-obsidian-markdown",
    name: "Format selection as Obsidian Markdown",
    mode: "obsidian-markdown"
  },
  {
    id: "organize-selection-as-note",
    name: "Organize selection as note",
    mode: "note-organize"
  },
  {
    id: "organize-selection-as-diary",
    name: "Organize selection as diary",
    mode: "diary-organize"
  },
  {
    id: "format-selection-as-course-note",
    name: "Format selection as course note",
    mode: "course-note"
  },
  {
    id: "compress-selection-into-review-card",
    name: "Compress selection into review card",
    mode: "review-card"
  },
  {
    id: "generate-wiki-candidates",
    name: "Generate Wiki candidates",
    mode: "wiki-candidates"
  },
  {
    id: "make-selection-concise",
    name: "Make selection concise",
    mode: "concise"
  }
];
function buildPromptMessages(systemPrompt, options) {
  return [
    {
      role: "system",
      content: systemPrompt.trim() || BASE_SYSTEM_PROMPT
    },
    {
      role: "user",
      content: buildUserPrompt(options)
    }
  ];
}
function buildMessages(systemPrompt, options) {
  return buildPromptMessages(systemPrompt, options);
}
function buildUserPrompt(options) {
  return [
    buildModePrompt(options.mode),
    buildUserInstructionBlock(options),
    buildContextBlock(options),
    buildInputBlock(options.selectedText)
  ].filter(Boolean).join("\n\n");
}
function buildModePrompt(mode) {
  if (mode === "obsidian-markdown") {
    return OBSIDIAN_MARKDOWN_PROMPT;
  }
  if (mode === "note-organize" || mode === "course-note") {
    return NOTE_ORGANIZE_PROMPT;
  }
  if (mode === "diary-organize") {
    return DIARY_ORGANIZE_PROMPT;
  }
  if (mode === "review-card") {
    return REVIEW_CARD_PROMPT;
  }
  if (mode === "wiki-candidates") {
    return WIKI_CANDIDATES_PROMPT;
  }
  if (mode === "concise") {
    return CONCISE_PROMPT;
  }
  return "\u4F60\u6B63\u5728\u6267\u884C\u201C\u81EA\u5B9A\u4E49\u6307\u4EE4\u6A21\u5F0F\u201D\u3002\u8BF7\u6309\u7528\u6237\u4E34\u65F6 instruction \u5904\u7406\u8F93\u5165\u6587\u672C\uFF0C\u4F46\u4ECD\u5FC5\u987B\u9075\u5B88 system message \u4E2D\u7684\u901A\u7528\u89C4\u5219\u3002";
}
function buildUserInstructionBlock(options) {
  var _a;
  const instruction = (_a = options.customInstruction) == null ? void 0 : _a.trim();
  if (!instruction) {
    return "";
  }
  return `\u7528\u6237\u4E34\u65F6 instruction\uFF1A
${instruction}`;
}
function buildInputBlock(selectedText) {
  return `\u8F93\u5165\u6587\u672C\uFF1A
${selectedText}`;
}
function buildContextBlock(options) {
  var _a;
  const sections = [];
  if ((_a = options.currentFileName) == null ? void 0 : _a.trim()) {
    sections.push(`\u5F53\u524D\u6587\u4EF6\u540D\uFF1A${options.currentFileName.trim()}`);
  }
  if (options.inputSource) {
    sections.push(
      inputSourceLabel(options.inputSource)
    );
  }
  return sections.length ? `\u4E0A\u4E0B\u6587\u4FE1\u606F\uFF1A
${sections.join("\n")}` : "";
}
function inputSourceLabel(source) {
  if (source === "manual") {
    return "\u8F93\u5165\u6765\u6E90\uFF1AManual input\uFF08\u7528\u6237\u5728\u4FA7\u680F\u624B\u52A8\u7C98\u8D34\u6216\u8F93\u5165\u7684\u6587\u672C\uFF09";
  }
  if (source === "note") {
    return "\u8F93\u5165\u6765\u6E90\uFF1ACurrent note fallback\uFF08\u5F53\u524D Markdown \u6587\u4EF6\u6B63\u6587\uFF0C\u5DF2\u79FB\u9664\u5F00\u5934 frontmatter \u548C\u4E00\u7EA7\u6807\u9898\uFF09";
  }
  return "\u8F93\u5165\u6765\u6E90\uFF1ACaptured selection\uFF08Obsidian \u7F16\u8F91\u5668\u4E2D\u7684\u9009\u4E2D\u6587\u672C\uFF09";
}

// src/api.ts
async function callChatCompletions(settings, promptOptions) {
  var _a, _b, _c;
  const { maxTokens, timeoutSeconds } = resolveModeRuntime(promptOptions.mode, settings);
  const controller = new AbortController();
  const timeout = window.setTimeout(
    () => controller.abort(),
    timeoutSeconds * 1e3
  );
  try {
    const response = await fetch(chatCompletionsUrl(settings.baseUrl), {
      method: "POST",
      headers: {
        Authorization: `Bearer ${settings.apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: settings.model,
        messages: buildMessages(settings.systemPrompt, promptOptions),
        temperature: settings.temperature,
        max_tokens: maxTokens
      }),
      signal: controller.signal
    });
    const text = await response.text();
    const data = parseJsonResponse(text);
    if (!response.ok) {
      throw new Error(statusToMessage(response.status, data));
    }
    const content = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
    if (!content || typeof content !== "string") {
      throw new Error("API returned an unexpected response format: missing choices[0].message.content.");
    }
    return stripCodeFence(content);
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new Error(
        `Timed out after ${timeoutSeconds}s. Model: ${settings.model}. Input: ${promptOptions.selectedText.length} chars. Max tokens: ${maxTokens}. Try increasing timeout to 60-90s or shortening the input.`
      );
    }
    throw error;
  } finally {
    window.clearTimeout(timeout);
  }
}
function chatCompletionsUrl(baseUrl) {
  return `${baseUrl.replace(/\/+$/, "")}/chat/completions`;
}
function parseJsonResponse(text) {
  if (!text.trim()) {
    return {};
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    throw new Error("API returned invalid JSON.");
  }
}
function stripCodeFence(text) {
  let cleaned = text.trim();
  const fenceStart = /^```[a-zA-Z]*\n/;
  const fenceEnd = /\n```$/;
  if (fenceStart.test(cleaned) && fenceEnd.test(cleaned)) {
    cleaned = cleaned.replace(fenceStart, "").replace(fenceEnd, "");
  }
  return cleaned.trim();
}
function statusToMessage(status, data) {
  var _a;
  const apiMessage = (_a = data.error) == null ? void 0 : _a.message;
  if (status === 401 || status === 403) {
    return "API authentication failed. Check your API key and access permissions.";
  }
  if (status === 429) {
    return "API rate limit reached. Please wait and try again.";
  }
  if (status === 404) {
    return "API endpoint returned 404. Check that Base URL is correct and only includes the API root, e.g. https://example.com/v1. Do not include /chat/completions.";
  }
  if (status >= 500) {
    return `API server error (${status}). Please try again later.`;
  }
  return apiMessage ? `API request failed: ${apiMessage}` : `API request failed with status ${status}.`;
}

// src/preview-modal.ts
var import_obsidian = require("obsidian");
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.originalText = options.originalText;
    this.resultText = options.resultText;
    this.showOriginal = options.showOriginal;
    this.onReplace = options.onReplace;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("format-assistant-preview");
    contentEl.createEl("h2", { text: "Preview formatted Markdown" });
    const grid = contentEl.createDiv({ cls: "format-assistant-preview__grid" });
    if (this.showOriginal) {
      this.createTextPane(grid, "Original selection", this.originalText);
    }
    this.createTextPane(grid, "Formatted result", this.resultText);
    const actions = contentEl.createDiv({ cls: "format-assistant-preview__actions" });
    const replaceButton = actions.createEl("button", {
      text: "Replace selection",
      cls: "mod-cta"
    });
    replaceButton.addEventListener("click", () => {
      this.onReplace();
      this.close();
    });
    const copyButton = actions.createEl("button", { text: "Copy result" });
    copyButton.addEventListener("click", async () => {
      await navigator.clipboard.writeText(this.resultText);
      new import_obsidian.Notice("Result copied.");
    });
    const cancelButton = actions.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
  createTextPane(parent, title, text) {
    const pane = parent.createDiv({ cls: "format-assistant-preview__pane" });
    pane.createEl("h3", { text: title });
    pane.createDiv({
      cls: "format-assistant-preview__text",
      text
    });
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.message = options.message;
    this.confirmText = options.confirmText;
    this.onConfirm = options.onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("format-assistant-confirm");
    contentEl.createEl("h2", { text: "Confirm change" });
    contentEl.createEl("p", { text: this.message });
    const actions = contentEl.createDiv({ cls: "format-assistant-preview__actions" });
    const confirmButton = actions.createEl("button", {
      text: this.confirmText,
      cls: "mod-cta"
    });
    confirmButton.addEventListener("click", () => {
      this.onConfirm();
      this.close();
    });
    const cancelButton = actions.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/sidebar-presets.ts
var MAX_PROMPT_PRESETS = 5;
function createPromptPreset(content) {
  const normalized = content.trim();
  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    name: toPresetName(normalized),
    content: normalized
  };
}
function normalizePromptPresets(value) {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item) => {
    return Boolean(
      item && typeof item.id === "string" && typeof item.name === "string" && typeof item.content === "string" && item.content.trim()
    );
  }).slice(0, MAX_PROMPT_PRESETS);
}
function toPresetName(content) {
  var _a, _b;
  const firstLine = (_b = (_a = content.split(/\r?\n/).find((line) => line.trim())) == null ? void 0 : _a.trim()) != null ? _b : "Prompt";
  return firstLine.length > 28 ? `${firstLine.slice(0, 28)}...` : firstLine;
}

// src/settings-types.ts
var DEFAULT_SYSTEM_PROMPT = BASE_SYSTEM_PROMPT;
var DEFAULT_SETTINGS = {
  baseUrl: "https://api.openai.com/v1",
  apiKey: "",
  model: "gpt-4o-mini",
  maxTokens: 1200,
  temperature: 0.2,
  providerType: "openai-compatible",
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  previewBeforeReplace: true,
  timeoutSeconds: 30,
  sidebarDefaultMode: "obsidian-markdown",
  autoUseSelectionOnSidebarOpen: false,
  includeCurrentFileNameInPrompt: true,
  includeFullCurrentNote: false,
  promptPresets: [],
  apiProfiles: [],
  activeApiProfileId: ""
};
function normalizeSettings(data) {
  const raw = typeof data === "object" && data !== null ? data : {};
  return {
    ...DEFAULT_SETTINGS,
    ...raw,
    promptPresets: normalizePromptPresets(raw.promptPresets),
    apiProfiles: normalizeApiProfiles(raw.apiProfiles),
    activeApiProfileId: typeof raw.activeApiProfileId === "string" ? raw.activeApiProfileId : ""
  };
}
function validateApiSettings(settings) {
  if (!settings.baseUrl.trim()) {
    return "API Base URL is required.";
  }
  if (settings.baseUrl.replace(/\/+$/, "").endsWith("/chat/completions")) {
    return "Base URL should not include /chat/completions. Use the API root such as https://example.com/v1.";
  }
  if (!settings.apiKey.trim()) {
    return "API key is required.";
  }
  if (!settings.model.trim()) {
    return "Model is required.";
  }
  if (settings.maxTokens < 1) {
    return "Max Tokens must be greater than 0.";
  }
  if (settings.timeoutSeconds < 1) {
    return "Timeout seconds must be greater than 0.";
  }
  return null;
}

// src/settings.ts
var FormatAssistantSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Format Assistant" });
    this.displayApiProfiles(containerEl);
    new import_obsidian2.Setting(containerEl).setName("API Base URL").setDesc("OpenAI-compatible API base URL, without /chat/completions.").addText(
      (text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API Key").setDesc("Stored in Obsidian plugin data. The plugin never logs this value.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Model").setDesc("Example: gpt-4o-mini.").addText(
      (text) => text.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim();
        await this.plugin.saveSettings();
        this.plugin.refreshSidebarViews();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Max Tokens").addText(
      (text) => text.setPlaceholder("1200").setValue(String(this.plugin.settings.maxTokens)).onChange(async (value) => {
        this.plugin.settings.maxTokens = this.toNumber(value, 1200, 1);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Temperature").addSlider(
      (slider) => slider.setLimits(0, 2, 0.1).setDynamicTooltip().setValue(this.plugin.settings.temperature).onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Provider Type").addDropdown(
      (dropdown) => dropdown.addOption("openai-compatible", "OpenAI-compatible").setValue(this.plugin.settings.providerType).onChange(async (value) => {
        this.plugin.settings.providerType = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("System Prompt").setDesc("Global rules sent with each formatting request.").addTextArea((text) => {
      text.inputEl.rows = 12;
      text.inputEl.cols = 60;
      text.inputEl.addClass("format-assistant-system-prompt-input");
      text.setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
    }).addButton(
      (button) => button.setButtonText("Reset to default").onClick(async () => {
        this.plugin.settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
        await this.plugin.saveSettings();
        const input = containerEl.querySelector(
          ".format-assistant-system-prompt-input"
        );
        if (input) {
          input.value = DEFAULT_SYSTEM_PROMPT;
        }
        new import_obsidian2.Notice("System prompt reset to default.");
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Preview before replace").setDesc("When enabled, the preview shows both original and formatted text. Replacement still always requires confirmation.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.previewBeforeReplace).onChange(async (value) => {
        this.plugin.settings.previewBeforeReplace = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Timeout seconds").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.timeoutSeconds)).onChange(async (value) => {
        this.plugin.settings.timeoutSeconds = this.toNumber(value, 30, 1);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto use selection on sidebar open").setDesc("When enabled, the sidebar reads the current editor selection as temporary context when opened.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoUseSelectionOnSidebarOpen).onChange(async (value) => {
        this.plugin.settings.autoUseSelectionOnSidebarOpen = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Include current file name in prompt").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeCurrentFileNameInPrompt).onChange(async (value) => {
        this.plugin.settings.includeCurrentFileNameInPrompt = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Allow current note fallback").setDesc("When enabled, Generate may use the active note body if no text is selected. The plugin never scans the vault.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeFullCurrentNote).onChange(async (value) => {
        this.plugin.settings.includeFullCurrentNote = value;
        await this.plugin.saveSettings();
        if (value) {
          new import_obsidian2.Notice("Current note fallback enabled. Only the active note can be used; the vault is never scanned.");
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Test API connection").setDesc("Sends a minimal chat completion request using the current settings.").addButton(
      (button) => button.setButtonText("Test").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Testing...");
        try {
          await this.plugin.testConnection();
          new import_obsidian2.Notice("API connection succeeded.");
        } catch (error) {
          new import_obsidian2.Notice(this.plugin.toUserError(error));
        } finally {
          button.setDisabled(false);
          button.setButtonText("Test");
        }
      })
    );
    containerEl.createDiv({
      cls: "format-assistant-setting-warning",
      text: "Format Assistant only sends selected text for the command or sidebar action you run. It does not scan your vault or batch-edit notes."
    });
  }
  displayApiProfiles(containerEl) {
    containerEl.createEl("h3", { text: "API Profiles" });
    new import_obsidian2.Setting(containerEl).setName("Active API profile").setDesc("Switch between saved API settings. API keys are stored in Obsidian plugin data with the profile settings and never logged.").addDropdown((dropdown) => {
      dropdown.addOption("", "Manual current settings");
      for (const profile of this.plugin.settings.apiProfiles) {
        dropdown.addOption(profile.id, profile.name);
      }
      dropdown.setValue(this.plugin.settings.activeApiProfileId).onChange(async (value) => {
        if (!value) {
          this.plugin.settings.activeApiProfileId = "";
          await this.plugin.saveSettings();
          this.plugin.refreshSidebarViews();
          return;
        }
        const profile = this.plugin.settings.apiProfiles.find((item) => item.id === value);
        if (!profile) {
          new import_obsidian2.Notice("API profile not found.");
          return;
        }
        await this.plugin.applyApiProfile(profile);
        this.display();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Save current API settings").setDesc(`${this.plugin.settings.apiProfiles.length}/${MAX_API_PROFILES} saved profiles. API keys are stored in Obsidian plugin data with the profile settings.`).addText((text) => {
      text.setPlaceholder("Profile name");
      text.inputEl.addClass("format-assistant-profile-name-input");
    }).addButton(
      (button) => button.setButtonText("Save").onClick(async () => {
        var _a;
        const input = containerEl.querySelector(
          ".format-assistant-profile-name-input"
        );
        const profileName = (_a = input == null ? void 0 : input.value) != null ? _a : "";
        if (this.plugin.settings.apiProfiles.length >= MAX_API_PROFILES) {
          new import_obsidian2.Notice(`API profiles are limited to ${MAX_API_PROFILES}.`);
          return;
        }
        const profile = createApiProfileFromSettings(
          this.plugin.settings,
          profileName
        );
        this.plugin.settings.apiProfiles = [
          ...this.plugin.settings.apiProfiles,
          profile
        ];
        this.plugin.settings.activeApiProfileId = profile.id;
        await this.plugin.saveSettings();
        this.plugin.refreshSidebarViews();
        new import_obsidian2.Notice("API profile saved.");
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Remove active API profile").setDesc("Removes the saved profile only. Current API fields stay unchanged.").addButton(
      (button) => button.setButtonText("Remove").setDisabled(!this.plugin.settings.activeApiProfileId).onClick(async () => {
        const id = this.plugin.settings.activeApiProfileId;
        if (!id) {
          return;
        }
        this.plugin.settings.apiProfiles = this.plugin.settings.apiProfiles.filter(
          (profile) => profile.id !== id
        );
        this.plugin.settings.activeApiProfileId = "";
        await this.plugin.saveSettings();
        this.plugin.refreshSidebarViews();
        new import_obsidian2.Notice("API profile removed.");
        this.display();
      })
    );
  }
  toNumber(value, fallback, min) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed) || parsed < min) {
      return fallback;
    }
    return parsed;
  }
};

// src/sidebar-view.ts
var import_obsidian4 = require("obsidian");

// src/selection-service.ts
var import_obsidian3 = require("obsidian");
var SelectionService = class {
  constructor(app) {
    this.lastMarkdownInfo = null;
    this.app = app;
  }
  rememberMarkdownInfo(editor, info) {
    if (!(info == null ? void 0 : info.file)) {
      return;
    }
    this.lastMarkdownInfo = {
      ...info,
      editor
    };
  }
  getLastMarkdownInfo() {
    return this.lastMarkdownInfo;
  }
  getActiveMarkdownInfo() {
    var _a;
    const activeEditor = this.app.workspace.activeEditor;
    if (activeEditor == null ? void 0 : activeEditor.editor) {
      return activeEditor;
    }
    return (_a = this.lastMarkdownInfo) != null ? _a : this.getActiveMarkdownView();
  }
  getActiveSelectionPreview(info = this.getActiveMarkdownInfo()) {
    var _a, _b, _c, _d, _e, _f;
    const text = (_b = (_a = info == null ? void 0 : info.editor) == null ? void 0 : _a.getSelection()) != null ? _b : "";
    return {
      source: "selection",
      fileName: (_d = (_c = info == null ? void 0 : info.file) == null ? void 0 : _c.basename) != null ? _d : "No active Markdown file",
      filePath: (_f = (_e = info == null ? void 0 : info.file) == null ? void 0 : _e.path) != null ? _f : null,
      text,
      wordCount: countWords(text),
      characterCount: text.length,
      from: (info == null ? void 0 : info.editor) ? info.editor.getCursor("from") : null,
      to: (info == null ? void 0 : info.editor) ? info.editor.getCursor("to") : null
    };
  }
  captureFromEditor(editor, view) {
    var _a, _b, _c, _d;
    const text = editor.getSelection();
    if (!text.trim()) {
      return null;
    }
    const info = view != null ? view : this.app.workspace.activeEditor;
    return {
      source: "selection",
      fileName: (_b = (_a = info == null ? void 0 : info.file) == null ? void 0 : _a.basename) != null ? _b : null,
      filePath: (_d = (_c = info == null ? void 0 : info.file) == null ? void 0 : _c.path) != null ? _d : null,
      text,
      wordCount: countWords(text),
      characterCount: text.length,
      from: editor.getCursor("from"),
      to: editor.getCursor("to")
    };
  }
  captureCurrentContext(allowNoteFallback) {
    var _a, _b, _c, _d;
    const info = this.getActiveMarkdownInfo();
    if (!(info == null ? void 0 : info.editor)) {
      return {
        input: null,
        error: "Switch to a Markdown editor first."
      };
    }
    const selection = this.getActiveSelectionPreview(info);
    if (selection.text.trim()) {
      return {
        input: selection,
        error: null
      };
    }
    if (!allowNoteFallback) {
      return {
        input: null,
        error: "No selection captured. Enable current note fallback in settings, or paste text into Manual Input."
      };
    }
    const noteText = cleanCurrentNoteBody(info.editor.getValue());
    if (!noteText.trim()) {
      return {
        input: null,
        error: "Select text first or open a note with body text."
      };
    }
    return {
      input: {
        source: "note",
        fileName: (_b = (_a = info.file) == null ? void 0 : _a.basename) != null ? _b : null,
        filePath: (_d = (_c = info.file) == null ? void 0 : _c.path) != null ? _d : null,
        text: noteText,
        wordCount: countWords(noteText),
        characterCount: noteText.length,
        from: null,
        to: null
      },
      error: null
    };
  }
  verifyCapturedSelection(input) {
    var _a;
    const info = this.getActiveMarkdownInfo();
    if (!(info == null ? void 0 : info.editor)) {
      return {
        state: null,
        error: "No active Markdown editor."
      };
    }
    if (!input || input.source !== "selection" || !input.from || !input.to) {
      return {
        state: null,
        error: "Please capture a selection first."
      };
    }
    if (input.filePath && ((_a = info.file) == null ? void 0 : _a.path) !== input.filePath) {
      return {
        state: null,
        error: "Active file changed. Please refresh selection."
      };
    }
    const currentSelection = info.editor.getSelection();
    const currentFrom = info.editor.getCursor("from");
    const currentTo = info.editor.getCursor("to");
    if (!currentSelection.trim()) {
      return {
        state: null,
        error: "Current editor has no selection. Please refresh selection."
      };
    }
    if (currentSelection !== input.text || !positionsEqual(currentFrom, input.from) || !positionsEqual(currentTo, input.to)) {
      return {
        state: null,
        error: "Selection changed. Please click Refresh selection before replacing."
      };
    }
    return {
      state: {
        editor: info.editor,
        from: currentFrom,
        to: currentTo
      },
      error: null
    };
  }
  getActiveMarkdownView() {
    return this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
  }
};
function describeInput(text) {
  return `${text.length} chars / ${countWords(text)} words`;
}
function getNoteBodyRange(editor) {
  const lastLine = Math.max(editor.lineCount() - 1, 0);
  let start = 0;
  if (editor.getLine(0).trim() === "---") {
    for (let i = 1; i <= lastLine; i++) {
      if (editor.getLine(i).trim() === "---") {
        start = i + 1;
        break;
      }
    }
  }
  let headingSkipped = false;
  while (start <= lastLine) {
    const line = editor.getLine(start);
    if (!headingSkipped && line.startsWith("# ")) {
      headingSkipped = true;
      start++;
      continue;
    }
    if (!line.trim()) {
      start++;
      continue;
    }
    break;
  }
  if (start > lastLine) {
    start = lastLine;
  }
  return {
    from: { line: start, ch: 0 },
    to: { line: lastLine, ch: editor.getLine(lastLine).length }
  };
}
function countWords(text) {
  return text.trim() ? text.trim().split(/\s+/).filter(Boolean).length : 0;
}
function countLines(text) {
  return text.trim() ? text.split(/\r?\n/).length : 0;
}
function cleanCurrentNoteBody(text) {
  return stripLeadingHeading(stripFrontmatter(text)).trim();
}
function stripFrontmatter(text) {
  return text.replace(/^\s*---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, "");
}
function stripLeadingHeading(text) {
  return text.replace(/^\s*# [^\r\n]*(?:\r?\n|$)/, "");
}
function positionsEqual(left, right) {
  return left.line === right.line && left.ch === right.ch;
}

// src/sidebar-view.ts
var FORMAT_ASSISTANT_VIEW_TYPE = "format-assistant-sidebar";
var SIDEBAR_MODES = [
  "obsidian-markdown",
  "note-organize",
  "diary-organize"
];
var MODE_HINTS = {
  "obsidian-markdown": "Light cleanup: tidy layout only, no restructuring.",
  "note-organize": "Structured: extract concepts / formulas / pitfalls, may add headings.",
  "diary-organize": "Diary: keep the original tone; preserve the timeline; pull out real to-dos."
};
var FormatAssistantSidebarView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.manualInput = "";
    this.customInstruction = "";
    this.currentContext = null;
    this.outputText = "";
    this.statusText = "";
    this.errorText = "";
    this.loading = false;
    this.completedMs = null;
    this.lastGenerationSource = null;
    this.customInputEl = null;
    this.manualInputEl = null;
    this.contextPanelEl = null;
    this.selectedPresetId = "";
    this.plugin = plugin;
    this.mode = SIDEBAR_MODES.includes(plugin.settings.sidebarDefaultMode) ? plugin.settings.sidebarDefaultMode : "obsidian-markdown";
  }
  getViewType() {
    return FORMAT_ASSISTANT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Format Assistant";
  }
  getIcon() {
    return "sparkles";
  }
  async onOpen() {
    this.captureCurrentSelection(false);
    this.render();
    this.refreshContextStatus();
    this.registerDomEvent(this.contentEl, "pointerenter", () => {
      this.refreshContextStatus();
    });
    if (this.plugin.settings.autoUseSelectionOnSidebarOpen) {
      this.useCurrentSelection(false);
    }
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("format-assistant-sidebar");
    this.contextPanelEl = null;
    this.renderHeader(root);
    this.renderApiProfileSelector(root);
    this.renderContextPreview(root);
    this.renderModeSelector(root);
    this.renderInput(root);
    this.renderActions(root);
    this.renderManualInput(root);
    this.renderPromptPresets(root);
    this.renderStatus(root);
  }
  createCollapsibleSection(root, title, open) {
    const details = root.createEl("details", { cls: "format-assistant-collapsible" });
    details.open = open;
    details.createEl("summary", {
      cls: "format-assistant-collapsible-summary",
      text: title
    });
    return details.createDiv({ cls: "format-assistant-panel" });
  }
  refreshContextStatus() {
    var _a, _b, _c, _d, _e, _f;
    const info = this.plugin.selectionService.getActiveMarkdownInfo();
    const selection = (_b = (_a = info == null ? void 0 : info.editor) == null ? void 0 : _a.getSelection()) != null ? _b : "";
    const activeName = (_f = (_e = (_c = this.currentContext) == null ? void 0 : _c.fileName) != null ? _e : (_d = info == null ? void 0 : info.file) == null ? void 0 : _d.basename) != null ? _f : "No active Markdown file";
    if (!this.currentContext) {
      this.statusText = selection.trim() ? `Active file: ${activeName}. Current editor has a selection.` : this.plugin.settings.includeFullCurrentNote ? `Active file: ${activeName}. Current note fallback is enabled.` : `Active file: ${activeName}. Select text or paste into Manual Input.`;
    }
    this.refreshContextPreview();
  }
  focusInput() {
    var _a;
    (_a = this.customInputEl) == null ? void 0 : _a.focus();
  }
  useCurrentSelection(showNotice = true) {
    var _a;
    if (!this.captureCurrentSelection(showNotice)) {
      return;
    }
    if (showNotice) {
      new import_obsidian4.Notice(
        ((_a = this.currentContext) == null ? void 0 : _a.source) === "note" ? "Current note body sent to Format Assistant." : "Selection sent to Format Assistant."
      );
    }
  }
  setContextFromEditor(editor, view, showNotice) {
    const context = this.plugin.selectionService.captureFromEditor(editor, view);
    if (!context) {
      this.setError("Please select text first.");
      if (showNotice) {
        new import_obsidian4.Notice("Please select text first.");
      }
      return;
    }
    this.currentContext = context;
    this.errorText = "";
    this.statusText = `Captured ${describeInput(context.text)}.`;
    this.render();
    if (showNotice) {
      new import_obsidian4.Notice("Selection sent to Format Assistant.");
    }
  }
  renderHeader(root) {
    const header = root.createDiv({ cls: "format-assistant-header" });
    const titleBlock = header.createDiv();
    titleBlock.createEl("h2", { text: "Format Assistant" });
    titleBlock.createDiv({
      cls: "format-assistant-model",
      text: this.plugin.settings.model || "No model configured"
    });
    const settingsButton = header.createEl("button", {
      text: "Open settings",
      cls: "format-assistant-small-button"
    });
    settingsButton.addEventListener("click", () => this.openSettings());
  }
  renderApiProfileSelector(root) {
    const panel = root.createDiv({ cls: "format-assistant-panel format-assistant-api-profile" });
    const header = panel.createDiv({ cls: "format-assistant-section-header" });
    header.createEl("h3", { text: "API" });
    header.createSpan({
      cls: "format-assistant-muted",
      text: this.plugin.settings.apiProfiles.length ? "Select profile" : "No profiles"
    });
    const select = panel.createEl("select", { cls: "format-assistant-select" });
    select.createEl("option", {
      text: "Manual current settings",
      value: ""
    });
    for (const profile of this.plugin.settings.apiProfiles) {
      const option = select.createEl("option", {
        text: profile.name,
        value: profile.id
      });
      option.selected = profile.id === this.plugin.settings.activeApiProfileId;
    }
    select.value = this.plugin.settings.activeApiProfileId;
    select.addEventListener("change", () => {
      void this.switchApiProfile(select.value);
    });
  }
  renderContextPreview(root) {
    const panel = root.createDiv({ cls: "format-assistant-panel" });
    this.contextPanelEl = panel;
    this.renderContextPreviewContent(panel);
  }
  renderContextPreviewContent(panel) {
    const header = panel.createDiv({ cls: "format-assistant-section-header" });
    header.createEl("h3", { text: "Context Preview" });
    const preview = this.getDisplayedContextPreview();
    const fileName = preview.fileName === "No active Markdown file" ? "None" : preview.fileName;
    const hasContent = Boolean(preview.text.trim());
    const meta = panel.createDiv({ cls: "format-assistant-context-meta" });
    meta.createSpan({ text: `Current file: ${fileName}` });
    meta.createSpan({ text: `Source: ${this.getCurrentInputSourceLabel()}` });
    if (hasContent) {
      meta.createSpan({
        text: `${preview.characterCount} chars / ${preview.wordCount} words / ${countLines(preview.text)} lines`
      });
    }
    if (!hasContent) {
      panel.createDiv({
        cls: "format-assistant-empty format-assistant-context-preview",
        text: "No context captured. Select text, then Use / Refresh."
      });
      this.renderSelectionControls(panel);
      return;
    }
    panel.createEl("pre", {
      cls: "format-assistant-context-preview",
      text: preview.text
    });
    this.renderSelectionControls(panel);
  }
  refreshContextPreview() {
    if (!this.contextPanelEl) {
      this.render();
      return;
    }
    this.contextPanelEl.empty();
    this.renderContextPreviewContent(this.contextPanelEl);
  }
  renderModeSelector(root) {
    var _a;
    const wrapper = root.createDiv({ cls: "format-assistant-mode-block" });
    const panel = wrapper.createDiv({ cls: "format-assistant-inline-field" });
    panel.createSpan({ text: "Mode:" });
    const select = panel.createEl("select", { cls: "format-assistant-select format-assistant-mode-select" });
    for (const mode of SIDEBAR_MODES) {
      select.createEl("option", {
        text: FORMAT_MODE_LABELS[mode],
        value: mode
      });
    }
    const hint = wrapper.createDiv({
      cls: "format-assistant-muted format-assistant-mode-hint",
      text: (_a = MODE_HINTS[this.mode]) != null ? _a : ""
    });
    select.value = this.mode;
    select.addEventListener("change", () => {
      var _a2;
      this.mode = select.value;
      this.plugin.settings.sidebarDefaultMode = this.mode;
      void this.plugin.saveSettings();
      hint.setText((_a2 = MODE_HINTS[this.mode]) != null ? _a2 : "");
      this.statusText = `Mode: ${FORMAT_MODE_LABELS[this.mode]}.`;
      this.errorText = "";
      this.render();
    });
  }
  renderManualInput(root) {
    const panel = this.createCollapsibleSection(
      root,
      "Manual Input",
      Boolean(this.manualInput.trim())
    );
    const manualStats = panel.createDiv({
      cls: "format-assistant-muted",
      text: this.getManualInputStatsText()
    });
    this.manualInputEl = panel.createEl("textarea", {
      cls: "format-assistant-textarea format-assistant-manual-input",
      attr: {
        placeholder: "Paste text to process instead of the selection. Takes priority when non-empty."
      }
    });
    this.manualInputEl.value = this.manualInput;
    const buttons = panel.createDiv({ cls: "format-assistant-button-row format-assistant-button-row--compact" });
    const clearButton = buttons.createEl("button", { text: "Clear manual input" });
    clearButton.disabled = !this.manualInput;
    clearButton.addEventListener("click", () => {
      this.manualInput = "";
      this.statusText = "Manual input cleared.";
      this.render();
    });
    this.manualInputEl.addEventListener("input", () => {
      var _a, _b;
      this.manualInput = (_b = (_a = this.manualInputEl) == null ? void 0 : _a.value) != null ? _b : "";
      manualStats.setText(this.getManualInputStatsText());
      clearButton.disabled = !this.manualInput;
      this.refreshContextPreview();
    });
  }
  renderInput(root) {
    const panel = root.createDiv({ cls: "format-assistant-panel" });
    panel.createEl("h3", { text: "Instruction" });
    this.customInputEl = panel.createEl("textarea", {
      cls: "format-assistant-textarea",
      attr: {
        placeholder: "Add temporary instructions, for example: keep it concise, preserve the original tone, or organize it as a clearer course note."
      }
    });
    this.customInputEl.value = this.customInstruction;
    this.customInputEl.addEventListener("input", () => {
      var _a, _b;
      this.customInstruction = (_b = (_a = this.customInputEl) == null ? void 0 : _a.value) != null ? _b : "";
    });
  }
  renderPromptPresets(root) {
    const panel = this.createCollapsibleSection(
      root,
      `Prompt Presets (${this.plugin.settings.promptPresets.length}/${MAX_PROMPT_PRESETS})`,
      false
    );
    const select = panel.createEl("select", { cls: "format-assistant-select" });
    select.createEl("option", {
      text: this.plugin.settings.promptPresets.length ? "Select a preset" : "No presets saved",
      value: ""
    });
    for (const preset of this.plugin.settings.promptPresets) {
      const option = select.createEl("option", {
        text: preset.name,
        value: preset.id
      });
      option.title = preset.content;
      option.selected = preset.id === this.selectedPresetId;
    }
    select.addEventListener("change", () => {
      this.selectedPresetId = select.value;
    });
    const buttons = panel.createDiv({ cls: "format-assistant-button-row format-assistant-button-row--compact" });
    const addButton = buttons.createEl("button", { text: "+ Save" });
    addButton.addEventListener("click", () => {
      void this.addCurrentInputAsPreset();
    });
    const selectButton = buttons.createEl("button", { text: "Use" });
    selectButton.disabled = !this.plugin.settings.promptPresets.length;
    selectButton.addEventListener("click", () => this.applySelectedPreset());
    const removeButton = buttons.createEl("button", { text: "Delete" });
    removeButton.disabled = !this.plugin.settings.promptPresets.length;
    removeButton.addEventListener("click", () => {
      void this.removeSelectedPreset();
    });
  }
  renderSelectionControls(parent) {
    const panel = parent.createDiv({ cls: "format-assistant-selection-controls" });
    panel.createEl("h3", { text: "Selection" });
    const buttons = panel.createDiv({ cls: "format-assistant-button-row format-assistant-button-row--compact" });
    const useButton = buttons.createEl("button", { text: "Use" });
    useButton.addEventListener("click", () => this.useCurrentSelection(true));
    const refreshButton = buttons.createEl("button", { text: "Refresh" });
    refreshButton.addEventListener("click", () => this.useCurrentSelection(true));
    const bodyButton = buttons.createEl("button", { text: "Note body" });
    bodyButton.setAttribute("aria-label", "Select note body");
    bodyButton.addEventListener("click", () => this.selectNoteBody());
    const clearButton = buttons.createEl("button", { text: "Clear" });
    clearButton.addEventListener("click", () => {
      this.currentContext = null;
      this.statusText = "Context cleared.";
      this.errorText = "";
      this.completedMs = null;
      this.render();
    });
  }
  selectNoteBody() {
    const info = this.plugin.selectionService.getActiveMarkdownInfo();
    if (!(info == null ? void 0 : info.editor)) {
      this.setError("Switch to a Markdown editor first.");
      new import_obsidian4.Notice("Switch to a Markdown editor first.");
      return;
    }
    const { from, to } = getNoteBodyRange(info.editor);
    const bodyText = info.editor.getRange(from, to);
    if (!bodyText.trim()) {
      this.setError("This note has no body text to select.");
      new import_obsidian4.Notice("This note has no body text to select.");
      return;
    }
    info.editor.setSelection(from, to);
    this.useCurrentSelection(true);
  }
  renderActions(root) {
    const generatePanel = root.createDiv({ cls: "format-assistant-action-group" });
    generatePanel.createEl("h3", { text: "Generate" });
    const generateButton = generatePanel.createEl("button", {
      text: this.loading ? "Generating..." : "Generate",
      cls: "mod-cta format-assistant-full-button"
    });
    generateButton.disabled = this.loading;
    generateButton.addEventListener("click", () => {
      void this.generate();
    });
    const resultPanel = root.createDiv({ cls: "format-assistant-action-group" });
    resultPanel.createEl("h3", { text: "Result" });
    const canCopy = Boolean(this.outputText) && !this.loading && !this.errorText;
    const canWriteSelection = canCopy && this.lastGenerationSource === "selection";
    const canClearOutput = Boolean(this.outputText) && !this.loading;
    this.renderResultOutput(resultPanel);
    const resultButtons = resultPanel.createDiv({ cls: "format-assistant-result-buttons" });
    const copyButton = resultButtons.createEl("button", {
      text: "Copy",
      cls: "format-assistant-result-copy"
    });
    copyButton.disabled = !canCopy;
    copyButton.addEventListener("click", () => {
      void this.copyResult();
    });
    const replaceButton = resultButtons.createEl("button", {
      text: "Replace",
      cls: "format-assistant-result-secondary"
    });
    replaceButton.setAttribute("aria-label", "Replace selection");
    replaceButton.disabled = !canWriteSelection;
    replaceButton.addEventListener("click", () => {
      this.confirmReplace();
    });
    const insertButton = resultButtons.createEl("button", {
      text: "Insert below",
      cls: "format-assistant-result-secondary"
    });
    insertButton.setAttribute("aria-label", "Insert below selection");
    insertButton.disabled = !canWriteSelection;
    insertButton.addEventListener("click", () => {
      this.confirmInsertBelow();
    });
    const cancelButton = resultButtons.createEl("button", {
      text: "Clear output",
      cls: "format-assistant-result-clear"
    });
    cancelButton.disabled = !canClearOutput;
    cancelButton.addEventListener("click", () => {
      this.outputText = "";
      this.errorText = "";
      this.statusText = "Output cleared.";
      this.loading = false;
      this.completedMs = null;
      this.render();
    });
  }
  renderResultOutput(parent) {
    if (this.completedMs !== null && this.lastGenerationSource) {
      const state = this.errorText ? "Failed from" : "Generated from";
      parent.createDiv({
        cls: "format-assistant-result-status",
        text: `Status: ${state} ${this.formatInputSource(this.lastGenerationSource)} \xB7 Completed in ${this.completedMs} ms`
      });
    }
    if (this.loading) {
      parent.createDiv({
        cls: "format-assistant-output format-assistant-output-state",
        text: "Generating..."
      });
      return;
    }
    if (this.errorText) {
      parent.createDiv({
        cls: "format-assistant-output format-assistant-output-state format-assistant-error",
        text: this.errorText
      });
      return;
    }
    if (!this.outputText) {
      parent.createDiv({
        cls: "format-assistant-empty format-assistant-output format-assistant-output-state",
        text: this.plugin.settings.includeFullCurrentNote ? "No result yet. Click Generate to process manual input, captured selection, or current note fallback." : "No result yet. Click Generate to process manual input or captured selection."
      });
      return;
    }
    parent.createEl("pre", {
      cls: "format-assistant-output",
      text: this.outputText
    });
  }
  renderStatus(root) {
    if (!this.plugin.settings.includeFullCurrentNote) {
      return;
    }
    const panel = root.createDiv({ cls: "format-assistant-status" });
    panel.createDiv({
      cls: "format-assistant-warning",
      text: "Current note fallback is on. With no selection, Generate may send the active note body only. The vault is never scanned."
    });
  }
  async generate() {
    const input = this.resolveInputForGenerate();
    if (!input) {
      this.setError("No input text. Select text in an editor or paste text into Manual Input.");
      new import_obsidian4.Notice("No input text. Select text in an editor or paste text into Manual Input.");
      return;
    }
    const validationError = this.plugin.validateApiSettings();
    if (validationError) {
      this.setError(validationError);
      new import_obsidian4.Notice(validationError);
      return;
    }
    this.loading = true;
    this.outputText = "";
    this.errorText = "";
    this.statusText = "Generating...";
    this.completedMs = null;
    this.lastGenerationSource = input.source;
    this.render();
    const startedAt = performance.now();
    try {
      this.outputText = await this.plugin.generateFromSelection(
        this.mode,
        input.text,
        this.customInstruction,
        input.currentFileName,
        input.source
      );
      this.completedMs = Math.round(performance.now() - startedAt);
      this.statusText = `Generated from: ${this.formatInputSource(input.source)}. Completed in ${this.completedMs} ms.`;
    } catch (error) {
      this.completedMs = Math.round(performance.now() - startedAt);
      this.errorText = this.plugin.toUserError(error);
      this.statusText = `Failed after ${this.completedMs} ms. Input source: ${this.formatInputSource(input.source)}. Input length: ${input.text.length} chars.`;
      new import_obsidian4.Notice(this.errorText);
    } finally {
      this.loading = false;
      this.render();
    }
  }
  async copyResult() {
    if (!this.outputText) {
      new import_obsidian4.Notice("No result to copy.");
      return;
    }
    await navigator.clipboard.writeText(this.outputText);
    this.statusText = "Result copied.";
    this.render();
    new import_obsidian4.Notice("Result copied.");
  }
  confirmReplace() {
    if (!this.outputText) {
      new import_obsidian4.Notice("No result to replace with.");
      return;
    }
    if (this.lastGenerationSource !== "selection") {
      new import_obsidian4.Notice("Replace selection is only available for captured selection results.");
      return;
    }
    new ConfirmModal(this.app, {
      message: "Replace the current selection with the generated result?",
      confirmText: "Replace selection",
      onConfirm: () => this.replaceSelection()
    }).open();
  }
  confirmInsertBelow() {
    if (!this.outputText) {
      new import_obsidian4.Notice("No result to insert.");
      return;
    }
    if (this.lastGenerationSource !== "selection") {
      new import_obsidian4.Notice("Insert below selection is only available for captured selection results.");
      return;
    }
    new ConfirmModal(this.app, {
      message: "Insert the generated result below the current selection?",
      confirmText: "Insert below selection",
      onConfirm: () => this.insertBelowSelection()
    }).open();
  }
  replaceSelection() {
    const selectionState = this.getVerifiedSelectionState();
    if (!selectionState) {
      return;
    }
    selectionState.editor.replaceRange(
      this.outputText,
      selectionState.from,
      selectionState.to
    );
    this.statusText = "Selection replaced.";
    this.render();
    new import_obsidian4.Notice("Selection replaced.");
  }
  insertBelowSelection() {
    const selectionState = this.getVerifiedSelectionState();
    if (!selectionState) {
      return;
    }
    selectionState.editor.replaceRange(
      `

${this.outputText}`,
      selectionState.to
    );
    this.statusText = "Result inserted below selection.";
    this.render();
    new import_obsidian4.Notice("Result inserted below selection.");
  }
  getVerifiedSelectionState() {
    var _a;
    const result = this.plugin.selectionService.verifyCapturedSelection(this.currentContext);
    if (!result.state) {
      const message = (_a = result.error) != null ? _a : "Please capture a selection first.";
      this.setError(message);
      new import_obsidian4.Notice(message);
      return null;
    }
    return result.state;
  }
  captureCurrentSelection(showNotice) {
    var _a;
    const result = this.plugin.selectionService.captureCurrentContext(
      this.plugin.settings.includeFullCurrentNote
    );
    if (!result.input) {
      this.currentContext = null;
      const message = (_a = result.error) != null ? _a : "Select text first or open a note with body text.";
      this.statusText = message;
      this.errorText = "";
      this.render();
      if (showNotice) {
        new import_obsidian4.Notice(message);
      }
      return false;
    }
    this.currentContext = result.input;
    this.statusText = result.input.source === "note" ? `Using current note fallback: ${describeInput(result.input.text)}.` : `Captured ${describeInput(result.input.text)}.`;
    this.errorText = "";
    this.render();
    return true;
  }
  resolveInputForGenerate() {
    var _a, _b, _c, _d, _e, _f;
    const manualText = this.manualInput.trim();
    if (manualText) {
      return {
        text: manualText,
        source: "manual",
        currentFileName: (_c = (_b = (_a = this.plugin.selectionService.getActiveMarkdownInfo()) == null ? void 0 : _a.file) == null ? void 0 : _b.basename) != null ? _c : void 0
      };
    }
    if (!((_d = this.currentContext) == null ? void 0 : _d.text.trim())) {
      this.captureCurrentSelection(false);
    }
    if ((_e = this.currentContext) == null ? void 0 : _e.text.trim()) {
      return {
        text: this.currentContext.text.trim(),
        source: this.currentContext.source,
        currentFileName: (_f = this.currentContext.fileName) != null ? _f : void 0
      };
    }
    return null;
  }
  getCurrentInputSourceLabel() {
    var _a, _b;
    if (this.manualInput.trim()) {
      return "Manual input";
    }
    if (((_a = this.currentContext) == null ? void 0 : _a.source) === "selection" && this.currentContext.text.trim()) {
      return "Captured selection";
    }
    if (((_b = this.currentContext) == null ? void 0 : _b.source) === "note" && this.currentContext.text.trim()) {
      return "Current note fallback";
    }
    if (this.plugin.selectionService.getActiveSelectionPreview().text.trim()) {
      return "Selection (uncaptured \u2014 click Use)";
    }
    return "None";
  }
  formatInputSource(source) {
    if (source === "manual") {
      return "Manual input";
    }
    if (source === "note") {
      return "Current note fallback";
    }
    return "Captured selection";
  }
  setError(message) {
    this.errorText = message;
    this.statusText = "";
    this.render();
  }
  getDisplayedContextPreview() {
    var _a;
    if ((_a = this.currentContext) == null ? void 0 : _a.text.trim()) {
      return this.currentContext;
    }
    return this.plugin.selectionService.getActiveSelectionPreview();
  }
  getManualInputStatsText() {
    return `Manual input: ${this.manualInput.length} chars / ${countWords(this.manualInput)} words / ${countLines(this.manualInput)} lines`;
  }
  openSettings() {
    var _a, _b;
    const appWithSettings = this.app;
    (_a = appWithSettings.setting) == null ? void 0 : _a.open();
    (_b = appWithSettings.setting) == null ? void 0 : _b.openTabById(this.plugin.manifest.id);
  }
  async switchApiProfile(profileId) {
    if (!profileId) {
      this.plugin.settings.activeApiProfileId = "";
      await this.plugin.saveSettings();
      this.plugin.refreshSidebarViews();
      new import_obsidian4.Notice("Using manual API settings.");
      return;
    }
    const profile = this.plugin.settings.apiProfiles.find((item) => item.id === profileId);
    if (!profile) {
      this.setError("API profile not found.");
      new import_obsidian4.Notice("API profile not found.");
      return;
    }
    await this.plugin.applyApiProfile(profile);
  }
  async addCurrentInputAsPreset() {
    const content = this.customInstruction.trim();
    if (!content) {
      this.setError("Enter an instruction before saving a preset.");
      new import_obsidian4.Notice("Enter an instruction before saving a preset.");
      return;
    }
    if (this.plugin.settings.promptPresets.length >= MAX_PROMPT_PRESETS) {
      this.setError(`Prompt presets are limited to ${MAX_PROMPT_PRESETS}.`);
      new import_obsidian4.Notice(`Prompt presets are limited to ${MAX_PROMPT_PRESETS}.`);
      return;
    }
    const preset = createPromptPreset(content);
    this.plugin.settings.promptPresets = [
      ...this.plugin.settings.promptPresets,
      preset
    ];
    this.selectedPresetId = preset.id;
    await this.plugin.saveSettings();
    this.statusText = "Prompt preset saved.";
    this.errorText = "";
    this.render();
    new import_obsidian4.Notice("Prompt preset saved.");
  }
  applySelectedPreset() {
    const preset = this.getSelectedPreset();
    if (!preset) {
      this.setError("Select a prompt preset first.");
      new import_obsidian4.Notice("Select a prompt preset first.");
      return;
    }
    this.customInstruction = preset.content;
    this.statusText = "Prompt preset loaded into input.";
    this.errorText = "";
    this.render();
    this.focusInput();
  }
  async removeSelectedPreset() {
    const preset = this.getSelectedPreset();
    if (!preset) {
      this.setError("Select a prompt preset first.");
      new import_obsidian4.Notice("Select a prompt preset first.");
      return;
    }
    this.plugin.settings.promptPresets = this.plugin.settings.promptPresets.filter(
      (item) => item.id !== preset.id
    );
    this.selectedPresetId = "";
    await this.plugin.saveSettings();
    this.statusText = "Prompt preset removed.";
    this.errorText = "";
    this.render();
    new import_obsidian4.Notice("Prompt preset removed.");
  }
  getSelectedPreset() {
    return this.plugin.settings.promptPresets.find(
      (preset) => preset.id === this.selectedPresetId
    );
  }
};

// src/main.ts
var FormatAssistantPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    this.selectionService = new SelectionService(this.app);
    await this.loadSettings();
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        this.rememberMarkdownInfo(editor, info);
        this.refreshSidebarContextViews();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian5.MarkdownView) {
          this.rememberMarkdownInfo(leaf.view.editor, leaf.view);
          this.refreshSidebarContextViews();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (view) {
          this.rememberMarkdownInfo(view.editor, view);
          this.refreshSidebarContextViews();
        }
      })
    );
    this.registerView(
      FORMAT_ASSISTANT_VIEW_TYPE,
      (leaf) => new FormatAssistantSidebarView(leaf, this)
    );
    this.addRibbonIcon("sparkles", "Format Assistant", () => {
      void this.openSidebar();
    });
    this.addCommand({
      id: "open-format-assistant-sidebar",
      name: "Open Format Assistant sidebar",
      callback: () => {
        void this.openSidebar();
      }
    });
    this.addCommand({
      id: "focus-format-assistant-input",
      name: "Focus Format Assistant input",
      callback: () => {
        void this.focusSidebarInput();
      }
    });
    this.addCommand({
      id: "send-selected-text-to-format-assistant",
      name: "Send selected text to Format Assistant",
      editorCallback: (editor, view) => {
        void this.sendSelectionToSidebar(editor, view instanceof import_obsidian5.MarkdownView ? view : null);
      }
    });
    for (const task of FORMAT_TASKS) {
      this.addCommand({
        id: task.id,
        name: task.name,
        editorCallback: (editor, view) => {
          void this.formatSelection(
            editor,
            view instanceof import_obsidian5.MarkdownView ? view : null,
            task.mode
          );
        }
      });
    }
    this.addSettingTab(new FormatAssistantSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(FORMAT_ASSISTANT_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = normalizeSettings(await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async applyApiProfile(profile) {
    applyApiProfile(this.settings, profile);
    await this.saveSettings();
    this.refreshSidebarViews();
    new import_obsidian5.Notice(`API profile switched: ${profile.name}`);
  }
  async openSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(FORMAT_ASSISTANT_VIEW_TYPE);
    let leaf = leaves.length > 0 ? leaves[0] : null;
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({
        type: FORMAT_ASSISTANT_VIEW_TYPE,
        active: true
      }));
    }
    if (!leaf) {
      new import_obsidian5.Notice("Could not open Format Assistant sidebar.");
      return null;
    }
    await this.app.workspace.revealLeaf(leaf);
    const view = leaf.view instanceof FormatAssistantSidebarView ? leaf.view : null;
    view == null ? void 0 : view.refreshContextStatus();
    if (this.settings.autoUseSelectionOnSidebarOpen) {
      view == null ? void 0 : view.useCurrentSelection(false);
    }
    return view;
  }
  async focusSidebarInput() {
    const view = await this.openSidebar();
    view == null ? void 0 : view.focusInput();
  }
  async sendSelectionToSidebar(editor, view) {
    this.rememberMarkdownInfo(editor, view);
    const sidebar = await this.openSidebar();
    if (!sidebar) {
      return;
    }
    const selection = editor.getSelection();
    if (!selection.trim()) {
      new import_obsidian5.Notice("Please select text before sending it to Format Assistant.");
      return;
    }
    sidebar.setContextFromEditor(editor, view, true);
  }
  refreshSidebarViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(FORMAT_ASSISTANT_VIEW_TYPE)) {
      if (leaf.view instanceof FormatAssistantSidebarView) {
        leaf.view.render();
      }
    }
  }
  refreshSidebarContextViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(FORMAT_ASSISTANT_VIEW_TYPE)) {
      if (leaf.view instanceof FormatAssistantSidebarView) {
        leaf.view.refreshContextStatus();
      }
    }
  }
  getLastMarkdownInfo() {
    return this.selectionService.getLastMarkdownInfo();
  }
  validateApiSettings() {
    return validateApiSettings(this.settings);
  }
  async generateFromSelection(mode, selectedText, customInstruction, currentFileName, inputSource = "selection") {
    const validationError = this.validateApiSettings();
    if (validationError) {
      throw new Error(validationError);
    }
    return callChatCompletions(this.settings, {
      mode,
      selectedText,
      inputSource,
      customInstruction,
      currentFileName: this.settings.includeCurrentFileNameInPrompt ? currentFileName : void 0
    });
  }
  async testConnection() {
    const validationError = this.validateApiSettings();
    if (validationError) {
      throw new Error(validationError);
    }
    await callChatCompletions(this.settings, {
      mode: "custom",
      selectedText: "Connection test. Reply with OK only.",
      customInstruction: "Reply with OK only."
    });
  }
  toUserError(error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      return `API request timed out after ${this.settings.timeoutSeconds}s. Try a shorter selection, lower max tokens, or increase Timeout to 60-90 seconds in settings.`;
    }
    if (error instanceof Error) {
      return error.message;
    }
    return "Formatting failed.";
  }
  async formatSelection(editor, view, mode) {
    var _a;
    this.rememberMarkdownInfo(editor, view);
    const selection = editor.getSelection();
    const selectionStart = editor.getCursor("from");
    const selectionEnd = editor.getCursor("to");
    if (!selection.trim()) {
      new import_obsidian5.Notice("Please select text before running Format Assistant.");
      return;
    }
    const validationError = this.validateApiSettings();
    if (validationError) {
      new import_obsidian5.Notice(validationError);
      return;
    }
    new import_obsidian5.Notice("Formatting selection...");
    try {
      const result = await this.generateFromSelection(
        mode,
        selection,
        "",
        (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.basename
      );
      new PreviewModal(this.app, {
        originalText: selection,
        resultText: result,
        showOriginal: this.settings.previewBeforeReplace,
        onReplace: () => {
          const currentRange = editor.getRange(selectionStart, selectionEnd);
          if (currentRange !== selection) {
            new import_obsidian5.Notice("Selection changed. Please select the text again.");
            return;
          }
          editor.replaceRange(result, selectionStart, selectionEnd);
          new import_obsidian5.Notice("Selection replaced.");
        }
      }).open();
    } catch (error) {
      new import_obsidian5.Notice(this.toUserError(error));
    }
  }
  rememberMarkdownInfo(editor, info) {
    this.selectionService.rememberMarkdownInfo(editor, info);
  }
};
