/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FormatAssistantPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SYSTEM_PROMPT = `\u4F60\u662F Obsidian Markdown \u7B14\u8BB0\u6574\u7406\u52A9\u624B\u3002
\u89C4\u5219\uFF1A
1. \u53EA\u8F93\u51FA\u6574\u7406\u540E\u7684 Markdown\u3002
2. \u4E0D\u8F93\u51FA bash\u3001shell\u3001\u7EC8\u7AEF\u547D\u4EE4\u3002
3. \u4E0D\u89E3\u91CA\u8FC7\u7A0B\u3002
4. \u4E0D\u8F93\u51FA\u957F\u7BC7\u80CC\u666F\u3002
5. \u4FDD\u7559\u539F\u6587\u542B\u4E49\uFF0C\u4E0D\u4E71\u6269\u5199\u3002
6. \u4FDD\u6301 Obsidian wikilink\u3001tag\u3001callout\u3001frontmatter \u517C\u5BB9\u3002
7. \u516C\u5F0F\u5728 Markdown \u4E2D\u4F7F\u7528 $...$ \u6216 $$...$$\u3002
8. \u9ED8\u8BA4\u4E2D\u6587\u8F93\u51FA\u3002
9. \u5982\u679C\u8F93\u5165\u5185\u5BB9\u660E\u663E\u4E0D\u8DB3\uFF0C\u53EA\u505A\u683C\u5F0F\u6574\u7406\uFF0C\u4E0D\u8865\u9020\u5185\u5BB9\u3002`;
var DEFAULT_SETTINGS = {
  baseUrl: "https://api.openai.com/v1",
  apiKey: "",
  model: "gpt-4o-mini",
  maxTokens: 1200,
  temperature: 0.2,
  providerType: "openai-compatible",
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  previewBeforeReplace: true,
  timeoutSeconds: 30
};
var FORMAT_TASKS = [
  {
    id: "format-selection-as-obsidian-markdown",
    name: "Format selection as Obsidian Markdown",
    taskPrompt: "\u8BF7\u5C06\u8F93\u5165\u6587\u672C\u6574\u7406\u4E3A\u6E05\u6670\u3001\u89C4\u8303\u3001\u9002\u5408 Obsidian \u7684 Markdown\u3002\u4FDD\u7559\u539F\u610F\u3001\u516C\u5F0F\u3001\u6761\u4EF6\u3001wikilink\u3001tag\u3001callout \u548C frontmatter\u3002"
  },
  {
    id: "format-selection-as-course-note",
    name: "Format selection as course note",
    taskPrompt: `\u8BF7\u5C06\u8F93\u5165\u6587\u672C\u6574\u7406\u4E3A\u8BFE\u7A0B\u7B14\u8BB0\uFF0C\u4E25\u683C\u4F7F\u7528\u4EE5\u4E0B Markdown \u7ED3\u6784\uFF1A
## \u6838\u5FC3\u6982\u5FF5
## \u516C\u5F0F\u4E0E\u6761\u4EF6
## \u5178\u578B\u9898\u5165\u53E3
## \u6613\u9519\u70B9
## \u5F85\u8FFD\u95EE\u95EE\u9898`
  },
  {
    id: "compress-selection-into-review-card",
    name: "Compress selection into review card",
    taskPrompt: `\u8BF7\u5C06\u8F93\u5165\u6587\u672C\u538B\u7F29\u4E3A Obsidian callout \u590D\u4E60\u5361\u7247\uFF0C\u4E25\u683C\u4F7F\u7528\u4EE5\u4E0B\u7ED3\u6784\uFF1A
> [!summary] \u590D\u4E60\u5361\u7247
> - \u6838\u5FC3\u7ED3\u8BBA\uFF1A
> - \u9002\u7528\u6761\u4EF6\uFF1A
> - \u5178\u578B\u9898\u578B\uFF1A
> - \u6613\u9519\u70B9\uFF1A`
  },
  {
    id: "generate-wiki-candidates",
    name: "Generate Wiki candidates",
    taskPrompt: `\u8BF7\u6839\u636E\u8F93\u5165\u6587\u672C\u751F\u6210\u6700\u591A 10 \u6761 Wiki \u5019\u9009\u6761\u76EE\uFF0C\u4E25\u683C\u8F93\u51FA Markdown \u8868\u683C\uFF1A
| \u7C7B\u578B | \u5019\u9009\u6807\u9898 | \u6765\u6E90\u4F9D\u636E | \u4E3A\u4EC0\u4E48\u503C\u5F97\u6C89\u6DC0 |
|---|---|---|---|

\u7C7B\u578B\u53EA\u80FD\u4ECE\u4EE5\u4E0B\u9009\u9879\u4E2D\u9009\u62E9\uFF1A
Concept, Formula, Method, Theorem, Problem, Comparison, Open Question`
  },
  {
    id: "make-selection-concise",
    name: "Make selection concise",
    taskPrompt: "\u8BF7\u5C06\u8F93\u5165\u6587\u672C\u7CBE\u7B80\u4E3A\u66F4\u77ED\u3001\u66F4\u6E05\u695A\u7684 Markdown\uFF0C\u4E0D\u4E22\u5931\u6838\u5FC3\u516C\u5F0F\u3001\u9002\u7528\u6761\u4EF6\u3001\u5B9A\u4E49\u3001\u9650\u5236\u548C\u5173\u952E\u7ED3\u8BBA\u3002"
  }
];
var FormatAssistantPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    for (const task of FORMAT_TASKS) {
      this.addCommand({
        id: task.id,
        name: task.name,
        editorCallback: (editor) => {
          void this.formatSelection(editor, task);
        }
      });
    }
    this.addSettingTab(new FormatAssistantSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async formatSelection(editor, task) {
    const selection = editor.getSelection();
    const selectionStart = editor.getCursor("from");
    const selectionEnd = editor.getCursor("to");
    if (!selection.trim()) {
      new import_obsidian.Notice("Please select text before running Format Assistant.");
      return;
    }
    const validationError = this.validateSettings();
    if (validationError) {
      new import_obsidian.Notice(validationError);
      return;
    }
    new import_obsidian.Notice("Formatting selection...");
    try {
      const result = await this.callChatCompletions(task.taskPrompt, selection);
      new PreviewModal(this.app, {
        originalText: selection,
        resultText: result,
        showOriginal: this.settings.previewBeforeReplace,
        onReplace: () => {
          editor.replaceRange(result, selectionStart, selectionEnd);
          new import_obsidian.Notice("Selection replaced.");
        }
      }).open();
    } catch (error) {
      new import_obsidian.Notice(this.toUserError(error));
    }
  }
  validateSettings() {
    if (!this.settings.baseUrl.trim()) {
      return "API Base URL is required.";
    }
    if (!this.settings.apiKey.trim()) {
      return "API key is required.";
    }
    if (!this.settings.model.trim()) {
      return "Model is required.";
    }
    if (this.settings.maxTokens < 1) {
      return "Max Tokens must be greater than 0.";
    }
    if (this.settings.timeoutSeconds < 1) {
      return "Timeout seconds must be greater than 0.";
    }
    return null;
  }
  async testConnection() {
    const validationError = this.validateSettings();
    if (validationError) {
      throw new Error(validationError);
    }
    await this.callChatCompletions(
      "\u8BF7\u53EA\u56DE\u590D\uFF1AOK",
      "\u8FDE\u63A5\u6D4B\u8BD5\u3002\u8BF7\u53EA\u56DE\u590D OK\u3002"
    );
  }
  async callChatCompletions(taskPrompt, selection) {
    var _a, _b, _c;
    const controller = new AbortController();
    const timeout = window.setTimeout(
      () => controller.abort(),
      this.settings.timeoutSeconds * 1e3
    );
    try {
      const response = await fetch(this.chatCompletionsUrl(), {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.settings.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: this.settings.model,
          messages: [
            {
              role: "system",
              content: this.settings.systemPrompt
            },
            {
              role: "user",
              content: `${taskPrompt}

\u8F93\u5165\u6587\u672C\uFF1A
${selection}`
            }
          ],
          temperature: this.settings.temperature,
          max_tokens: this.settings.maxTokens
        }),
        signal: controller.signal
      });
      const text = await response.text();
      const data = this.parseJsonResponse(text);
      if (!response.ok) {
        throw new Error(this.statusToMessage(response.status, data));
      }
      const content = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
      if (!content || typeof content !== "string") {
        throw new Error("API returned an unexpected response format.");
      }
      return content.trim();
    } finally {
      window.clearTimeout(timeout);
    }
  }
  chatCompletionsUrl() {
    return `${this.settings.baseUrl.replace(/\/+$/, "")}/chat/completions`;
  }
  parseJsonResponse(text) {
    if (!text.trim()) {
      return {};
    }
    try {
      return JSON.parse(text);
    } catch (e) {
      throw new Error("API returned invalid JSON.");
    }
  }
  statusToMessage(status, data) {
    var _a;
    const apiMessage = (_a = data.error) == null ? void 0 : _a.message;
    if (status === 401 || status === 403) {
      return "API authentication failed. Check your API key and access permissions.";
    }
    if (status === 429) {
      return "API rate limit reached. Please wait and try again.";
    }
    if (status >= 500) {
      return "API server error. Please try again later.";
    }
    return apiMessage ? `API request failed: ${apiMessage}` : `API request failed with status ${status}.`;
  }
  toUserError(error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      return "API request timed out.";
    }
    if (error instanceof Error) {
      return error.message;
    }
    return "Formatting failed.";
  }
};
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.originalText = options.originalText;
    this.resultText = options.resultText;
    this.showOriginal = options.showOriginal;
    this.onReplace = options.onReplace;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("format-assistant-preview");
    contentEl.createEl("h2", { text: "Preview formatted Markdown" });
    const grid = contentEl.createDiv({ cls: "format-assistant-preview__grid" });
    if (this.showOriginal) {
      this.createTextPane(grid, "Original selection", this.originalText);
    }
    this.createTextPane(grid, "Formatted result", this.resultText);
    const actions = contentEl.createDiv({ cls: "format-assistant-preview__actions" });
    const replaceButton = actions.createEl("button", {
      text: "Replace selection",
      cls: "mod-cta"
    });
    replaceButton.addEventListener("click", () => {
      this.onReplace();
      this.close();
    });
    const copyButton = actions.createEl("button", { text: "Copy result" });
    copyButton.addEventListener("click", async () => {
      await navigator.clipboard.writeText(this.resultText);
      new import_obsidian.Notice("Result copied.");
    });
    const cancelButton = actions.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
  createTextPane(parent, title, text) {
    const pane = parent.createDiv({ cls: "format-assistant-preview__pane" });
    pane.createEl("h3", { text: title });
    pane.createDiv({
      cls: "format-assistant-preview__text",
      text
    });
  }
};
var FormatAssistantSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Format Assistant" });
    new import_obsidian.Setting(containerEl).setName("API Base URL").setDesc("OpenAI-compatible API base URL, without /chat/completions.").addText(
      (text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Stored in Obsidian plugin data. The plugin never logs this value.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Model").setDesc("Example: gpt-4o-mini.").addText(
      (text) => text.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Tokens").addText(
      (text) => text.setPlaceholder("1200").setValue(String(this.plugin.settings.maxTokens)).onChange(async (value) => {
        this.plugin.settings.maxTokens = this.toNumber(value, 1200, 1);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Temperature").addSlider(
      (slider) => slider.setLimits(0, 2, 0.1).setDynamicTooltip().setValue(this.plugin.settings.temperature).onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Provider Type").addDropdown(
      (dropdown) => dropdown.addOption("openai-compatible", "OpenAI-compatible").setValue(this.plugin.settings.providerType).onChange(async (value) => {
        this.plugin.settings.providerType = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("System Prompt").setDesc("Global rules sent with each formatting request.").addTextArea((text) => {
      text.inputEl.rows = 12;
      text.inputEl.cols = 60;
      text.setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Preview before replace").setDesc("When enabled, the preview shows both original and formatted text. Replacement still always requires confirmation.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.previewBeforeReplace).onChange(async (value) => {
        this.plugin.settings.previewBeforeReplace = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Timeout seconds").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.timeoutSeconds)).onChange(async (value) => {
        this.plugin.settings.timeoutSeconds = this.toNumber(value, 30, 1);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Test API connection").setDesc("Sends a minimal chat completion request using the current settings.").addButton(
      (button) => button.setButtonText("Test").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Testing...");
        try {
          await this.plugin.testConnection();
          new import_obsidian.Notice("API connection succeeded.");
        } catch (error) {
          new import_obsidian.Notice(this.plugin.toUserError(error));
        } finally {
          button.setDisabled(false);
          button.setButtonText("Test");
        }
      })
    );
    containerEl.createDiv({
      cls: "format-assistant-setting-warning",
      text: "Format Assistant only sends the selected text for the command you run. It does not scan your vault or batch-edit notes."
    });
  }
  toNumber(value, fallback, min) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed) || parsed < min) {
      return fallback;
    }
    return parsed;
  }
};
